language: rust
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo test --all-features

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: orgize
  on:
    condition: "$TRAVIS_RUST_VERSION == stable"

notifications:
  email:
    on_failure: change
    on_success: change
