language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo test --all-features

notifications:
  email:
    on_failure: change
    on_success: change
