[package]
name = "orgize"
version = "0.1.1"
authors = ["PoiScript <poiscript@gmail.com>"]
description = "A Rust library for parsing orgmode files."
repository = "https://github.com/PoiScript/orgize"
readme = "README.md"
license = "MIT"
keywords = ["orgmode","emacs","parser"]

[badges]
travis-ci = { repository = "PoiScript/orgize" }

[dependencies]
jetscii = "0.4.3"
memchr = "2"
