name: Rust

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run rustfmt
        run: cargo fmt -- --check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache target/
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Test
        run: cargo test --all-features
